### ISSUE TITLE
Update typings for p5 version 1.0.0

### ISSUE THREAD

**Issue by davvidess** [p5-types/p5.ts#18]
Could you please update the typings for the new p5js version?

When I tried it myself I got

```
% npm run generate

> p5.ts@1.0.0 generate /Users/david/Desktop/p5.ts-master
> node src/cli.js generate

/Users/david/Desktop/p5.ts-master/node_modules/yargs/yargs.js:1133
      else throw err
           ^

TypeError: Cannot read property 'replace' of undefined
    at patchItemFile (/Users/david/Desktop/p5.ts-master/src/generate-typescript-annotations.js:22:35)
    at patchYUIDocs (/Users/david/Desktop/p5.ts-master/src/generate-typescript-annotations.js:45:7)
    at gta (/Users/david/Desktop/p5.ts-master/src/generate-typescript-annotations.js:770:3)
    at Object.exports.handler (/Users/david/Desktop/p5.ts-master/src/commands/generate.js:35:3)
    at Object.runCommand (/Users/david/Desktop/p5.ts-master/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/david/Desktop/p5.ts-master/node_modules/yargs/yargs.js:1046:30)
    at Object.parse (/Users/david/Desktop/p5.ts-master/node_modules/yargs/yargs.js:551:25)
    at Object.<anonymous> (/Users/david/Desktop/p5.ts-master/src/cli.js:4:4)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! p5.ts@1.0.0 generate: `node src/cli.js generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the p5.ts@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2020-04-04T15_10_29_013Z-debug.log
```

**Comment by Zalastax** [comment]
Blocked by https://github.com/p5-types/p5.ts/issues/24
