### ISSUE TITLE
fix dtslint

### ISSUE THREAD

**Issue by wuyudi** [p5-types/p5.ts#87]
I am trying to fix dtslint.

after `wget https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/notNeededPackages.json`, and `npm run dtslint`, I get the following errors.

```sh
❯ npm run dtslint

> p5.ts@1.0.0 dtslint
> dtslint types/p5

dtslint@0.0.141
Error: /home/asukaminato/p5.ts/types/p5/constants.d.ts:69:17
ERROR: 69:17  expect     TypeScript@5.0 compile error: 
Cannot find name 'VIDEO'.
ERROR: 69:25  expect     TypeScript@5.0 compile error: 
Cannot find name 'AUDIO'.

/home/asukaminato/p5.ts/types/p5/test/index.ts:36:45
ERROR: 36:45  semicolon  Missing semicolon

/home/asukaminato/p5.ts/types/p5/test/unaugmented.ts:5:15
ERROR: 5:15   expect     TypeScript@5.0 compile error: 
Namespace 'p5' has no exported member 'FFT'.
ERROR: 7:17   expect     TypeScript@5.0 compile error: 
Namespace 'p5' has no exported member 'Noise'.
ERROR: 9:18   expect     TypeScript@5.0 compile error: 
Namespace 'p5' has no exported member 'BandPass'.
ERROR: 15:21  expect     TypeScript@5.0 compile error: 
Property 'BandPass' does not exist on type 'typeof import("/home/asukaminato/p5.ts/types/p5/index.d.ts")'.
ERROR: 18:20  expect     TypeScript@5.0 compile error: 
Property 'Noise' does not exist on type 'typeof import("/home/asukaminato/p5.ts/types/p5/index.d.ts")'.
ERROR: 26:18  expect     TypeScript@5.0 compile error: 
Property 'FFT' does not exist on type 'typeof import("/home/asukaminato/p5.ts/types/p5/index.d.ts")'.

/home/asukaminato/p5.ts/types/p5/constants.d.ts
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/index.d.ts
  64:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/literals.d.ts
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/accessibility/describe.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/accessibility/outputs.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/color/creating_reading.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/color/p5.Color.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/color/setting.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/constants.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/environment.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/p5.Element.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/p5.Graphics.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/p5.Renderer.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/rendering.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/shape/2d_primitives.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/shape/attributes.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/shape/curves.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/shape/vertex.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/structure.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/core/transform.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/data/local_storage.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/data/p5.TypedDict.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/dom/dom.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/events/acceleration.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/events/keyboard.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/events/mouse.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/events/touch.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/image/image.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/image/loading_displaying.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/image/p5.Image.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/image/pixels.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/io/files.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/io/p5.Table.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/io/p5.TableRow.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/io/p5.XML.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/math/calculation.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/math/math.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/math/noise.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/math/p5.Vector.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/math/random.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/math/trigonometry.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/typography/attributes.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/typography/loading_displaying.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/typography/p5.Font.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/utilities/array_functions.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/utilities/conversion.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/utilities/string_functions.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/utilities/time_date.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/3d_primitives.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/interaction.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/light.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/loading.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/material.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/p5.Camera.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/p5.Geometry.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/p5.RendererGL.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/src/webgl/p5.Shader.d.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/test/index.ts
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/asukaminato/p5.ts/types/p5/test/unaugmented.ts
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 59 problems (59 errors, 0 warnings)

    at testTypesVersion (/home/asukaminato/p5.ts/node_modules/@definitelytyped/dtslint/dist/index.js:194:15)
    at async runTests (/home/asukaminato/p5.ts/node_modules/@definitelytyped/dtslint/dist/index.js:170:13)
    at async main (/home/asukaminato/p5.ts/node_modules/@definitelytyped/dtslint/dist/index.js:79:9)
```

any ideas?

I found this, but not work.

https://stackoverflow.com/questions/40029113/syntaxerror-import-and-export-may-appear-only-with-sourcetype-module-g

Or, can we ignore this test?

**Comment by wuyudi** [comment]
it stuck https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63913 ... I give up.

**Comment by wuyudi** [comment]
ignore it, since the manual patch works now. :)
